//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBox
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmBoxEntities : DbContext
    {
        public FilmBoxEntities()
            : base("name=FilmBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camera> Camera { get; set; }
        public virtual DbSet<Developer> Developer { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Lens> Lens { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Roll> Roll { get; set; }
        public virtual DbSet<RollTag> RollTag { get; set; }
        public virtual DbSet<Speed> Speed { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
    }
}
