//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public int Roll_Id { get; set; }
        public string Caption { get; set; }
        public string ImageDirectory { get; set; }
        public string ImageLink { get; set; }
    
        public virtual Roll Roll { get; set; }
    }
}
