//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roll()
        {
            this.Image = new HashSet<Image>();
            this.RollTag = new HashSet<RollTag>();
        }
    
        public int Id { get; set; }
        public int SerialNumber { get; set; }
        public int Film_Id { get; set; }
        public int Camera_Id { get; set; }
        public int Lens_Id { get; set; }
        public int Speed_Id { get; set; }
        public bool IsExpired { get; set; }
        public string Remark { get; set; }
        public bool IsDeveloped { get; set; }
        public Nullable<int> Developer_Id { get; set; }
    
        public virtual Camera Camera { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual Film Film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image { get; set; }
        public virtual Lens Lens { get; set; }
        public virtual Speed Speed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollTag> RollTag { get; set; }
    }
}
